#!/bin/bash
# Get latest crash report from device and symbolicate
# By Adam D <http://adam.hbang.ws>
# Licensed under the Apache License 2.0 <https://www.apache.org/licenses/LICENSE-2.0.html>

if [[ "$1" == "--help" ]]; then
	echo "Usage: $(basename "$0") [app]"
	echo
	echo "Get the latest crash report from the device and symbolicate it. Requires the"
	echo "symbolicate package by ashikase to be installed."
	echo "[app] is optionally the name of the executable that crashed, otherwise the"
	echo "very latest crash report is used."
	echo
	echo "The IP used is your \$THEOS_DEVICE_IP and \$THEOS_DEVICE_PORT, which is"
	echo "currently \"$THEOS_DEVICE_IP:$THEOS_DEVICE_PORT\"."
	exit 1
else
	name=

	if [[ "$1" != "" ]]; then
		name="-$1"
	fi

	ssh -p "$THEOS_DEVICE_PORT" root@"$THEOS_DEVICE_IP" "symbolicate /var/mobile/Library/Logs/CrashReporter/LatestCrash$name.*"
fi
