#!/bin/bash
# Transfer last picture in camera roll
# By Adam D <http://adam.hbang.ws>
# Licensed under the Apache License 2.0 <https://www.apache.org/licenses/LICENSE-2.0.html>

if [[ "$1" == "--help" ]]; then
	echo "Usage: $(basename "$0") [deviceip]"
	echo "Image is saved to your current directory."
	echo "Default IP is your \$THEOS_DEVICE_IP, which is currently \"$THEOS_DEVICE_IP\"."
	exit 1
else
	[[ "$1" == "" ]] && ip="$THEOS_DEVICE_IP" || ip="$1"

	lastplist=/var/mobile/Media/PhotoData/MISC/DCIM_APPLE.plist
	IFS=' ' read -r lastdir lastfile < <(ssh root@"$ip" "plutil -key DCIMLastDirectoryNumber \"$lastplist\" && plutil -key DCIMLastFileNumber \"$lastplist\"" | tr $'\n' ' ')

	scp root@"$ip":/var/mobile/Media/DCIM/"$lastdir"APPLE/IMG_$(printf "%04d" "$lastfile").* . || exit 2
fi
